// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://cplhariscvfxxohkydsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwbGhhcmlzY3ZmeHhvaGt5ZHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5NjU0ODAsImV4cCI6MjA5MTU0MTQ4MH0.SeD0MzTpB03VkQRgRwggWFj97Qnd4ODeZwpmhz1sbGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);